name: jupyterlab-maxfordham
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
  - http://10.10.30.125:8000
dependencies:
  - python==3.9
  - numpy
  - pandas
  - sympy
  - unyt
  - scipy
  - scikit-learn
  - scikit-image
  - ipyrun>=0.4.2
  - ipyautoui>=0.2.7
  - mfom==0.5.3
  - jupyter
  - notebook
  - jupyterlab
  - jupyterlab-system-monitor
  - jupyterlab-tour
  - jupyterlab-snippets
  - jupyterlab-spellchecker
  - jupyterlab-favorites
  - jupyterlab-recents
  - search-replace
  - jlab-image-editor
  - jupytext
  - jupyterlab-lsp
  - python-lsp-server
  - jupyterlab-spreadsheet-editor
  - jupyterlab-theme-toggle
  - jupyterlab-plotly
  - jupyterlab-geojson
  - jupyterlab-mathjax3
  - jupyterlab-katex
  - jupyterlab-search-replace 
  - jupyterlab-code-formatter
  - jupyterlab_commands
  - black
  - nb_black
  - ripgrep
  - ipympl
  #- jupyterlab-unfold
  #- jupyter-archive
  #- jupyterlab-cell-flash
  - theme-darcula
  - ipython
  - docrepr 
  - jupyterlab_pygments
  - ipywidgets 
  - ipydatagrid 
  - ipyvuetify
  - watchdog
  - plotly
  - vega
  - vegafusion-jupyter
  - vegafusion
  - kaleido
  - matplotlib
  - palettable
  - altair
  - vega
  - vega_datasets
  - pillow
  - seaborn
  - voila
  - line_profiler
  - memory_profiler
  - numexpr
  - pandas-datareader
  - netcdf4
  - openpyxl
  - myst-nb # for docs
  - jupyter-book # for docs
  - sphinx # for docs
  - sphinx-book-theme # for docs
  - sphinx-autoapi
  - sphinxcontrib-mermaid
  - sphinx-design
  - sphinx-togglebutton
  - autodoc-pydantic
  - xlsxwriter
  - xmltodict
  - pillow
  - jsonschema2md
  - pip
  - pip:
    - traitlets-paths
    - seedir
    - devtools[pygments]
    - pandoc-docx-pagebreak
    - sphinx_github_changelog
    - lckr-jupyterlab-variableinspector
    - git+https://github.com/jgunstone/xlsxtemplater.git@v0.1.6
