name: jlab-mxf
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - python
  - numpy
  - pandas
  - polars
  - sympy
  - anaconda
  - unyt
  - scipy
  - scikit-learn
  - scikit-learn-intelex
  - scikit-image
  # - mfom==0.5.3 # how to do this?
  - jupyter
  - xeus-python
  - notebook
  - jupyterlab
  - jupyterlab-system-monitor
  - jupyterlab-tour
  - jupyterlab-snippets
  - jupyterlab-spellchecker
  - jupyterlab-favorites
  - jupyterlab-recents
  - jupytext
  - jupyterlab-lsp
  - python-lsp-server
  - jupyterlab-plotly-extension
  - jupyterlab-geojson
  - jupyterlab-mathjax3
  - jupyterlab-katex
  - ripgrep
  - jupyterlab-search-replace 
  - jupyterlab_commands
  - jupyterlab_code_formatter
  - black
  - isort
  - nb_black
  - ipympl
  - jupyter-archive
  #- jupyterlab-unfold
  #- jupyterlab-cell-flash
  - theme-darcula
  - ipython
  - docrepr 
  - jupyterlab_pygments
  - ipywidgets
  - ipydatagrid
  - ipycanvas
  - ipycytoscape
  - ipyfilechooser
  - ipyvue
  - ipyvuetify
  - reacton
  - watchdog
  - plotly
  - python-kaleido
  - plotly-geo
  - vega
  - vegafusion-jupyter
  - vegafusion
  - vegafusion-python-embed
  - python-duckdb
  - matplotlib
  - palettable
  - altair
  - vega
  - vega_datasets
  - pillow
  - seaborn
  - voila
  - pythreejs
  - line_profiler
  - memory_profiler
  - numexpr
  - pandas-datareader
  - netcdf4
  - openpyxl
  - myst-nb # for docs
  - jupyter-book # for docs
  - sphinx # for docs
  - sphinx-book-theme # for docs
  - sphinx-autoapi
  - sphinxcontrib-mermaid
  - sphinx-design
  - sphinx-togglebutton
  - autodoc-pydantic
  - xlsxwriter
  - xmltodict
  - pillow
  - jsonschema2md
  - pip
  - pip:
    - jupyterlab_image_editor
    - jupyterlab-spreadsheet-editor
    - vl-convert-python
    - ipyobservable
    # - jupyterlab-topbar
    - traitlets-paths
    - seedir
    - emoji
    - mosaic-widget
    - devtools[pygments]
    - pandoc-docx-pagebreak
    - sphinx_github_changelog
    - lckr-jupyterlab-variableinspector
    - ipyautoui==0.4.8
    - git+https://github.com/maxfordham/xlsxtemplater.git@v0.1.6
    - git+https://github.com/maxfordham/ipyrun.git@0.4.2
